name: "Lokalise Sync"
description: "Sync translations with lokalise.com"
inputs:
  api-token:
    description: "Lokalise Api token"
    required: true
  project-id:
    description: "Lokalise project id"
    required: true
  dir-path:
    description: "translation file dir from project root"
    required: true

outputs:
  uploaded-files:
    description: "Summary of files uploaded"

runs:
  using: 'node16'
  main: 'dist/index.js'